apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:17
        name: postgres
        resources: {}
        env:
        - name: POSTGRES_PASSWORD
          value: "12345"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dbdata
          subPath: data
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: db-pvc



