apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app-srv
  namespace: group-n
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: test-app
  type: ClusterIP
