apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
  namespace: group-n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: experimentacr.azurecr.io/demo-app:latest
        name: demo-app
        ports:
          - containerPort: 8000
        env:
          - name: APP_NAME
            value: "demo_app_group_n"

